---
title: "Indirect SNPs for metabolite traits"
author: "Jinliang Yang"
date: "10-20-2020"
output: NULL
---


## Normalize the path:

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) 
knitr::opts_knit$set(root.dir=normalizePath('../../')) 
```

### Results generated by Zhikai

/common/jyanglab/zhikaiyang/projects/mediation/largedata/med_output

fixed_dsnps : direct snps
fixed_indirect : indirect snps
fixed_mediator_trait : mediator for agronomic traits
fixed_mediator_X...: mediator for metabolic traits
fixe.pcut_sum : pvm


### Indirect SNPs

```{r}

f <- list.files(path="/common/jyanglab/zhikaiyang/projects/mediation/largedata/med_output/", pattern="indirect_", full.names = T)

out <- data.frame()
for(i in 1:length(f)){
  tem <- read.csv(f[i], header=TRUE)
  tem$file <- f[i]
  out <- rbind(out, tem)
}

out$file  <- gsub(".*\\/", "", out$file)
# method
out$method <- gsub("_.*", "", out$file)
# tissue type
out$tissue <- gsub(".*_ts_|.csv", "", out$file)
table(out$tissue)
# trait
out$trait <- gsub(".*indirect_|_ts.*", "", out$file)
table(out$trait)

write.table(out, "cache/indirect_SNPs_55258rows.csv", sep=",", row.names=FALSE, quote=FALSE)
```

------------------

Back to the local computer!


```{r}
library("data.table")

id <- fread("cache/indirect_SNPs_55258rows.csv", header=TRUE, data.table=FALSE)

# Unique mediators
length(unique(id$medi)) #1656

tb <- data.frame(table(id$snps_for_medi))
tb <- tb[order(tb$Freq, decreasing = T),]
sub <- subset(tb, Freq > 1)
dim(sub)
```

### AC148152.3_FG005

```{r}
fg005 <- subset(id, medi %in% "AC148152.3_FG005")

tb2 <- data.frame(table(fg005$snps_for_medi))
tb2 <- tb2[order(tb2$Freq, decreasing = T),]
sub <- subset(tb, Freq > 1)
```



```{r}

mg <- read.csv("data/med_master_table_fixed.csv")

mgt <- data.frame(table(mg$gene3))
mgt <- mgt[order(mgt$Freq, decreasing = T),]

hlgene <- subset(mg, gene3 %in% mgt$Var1[1])

### from the top10 indirect SNPs, which ones contain the FG008
fg008 <- subset(med_top10, medi %in% hlgene$gene3)
### deduplicated
fg008 <- fg008[!duplicated(fg008$snps_for_medi),]

fg008$chr <- as.numeric(as.character(gsub("-.*", "", fg008$snps_for_medi)))
fg008$pos <- as.numeric(as.character(gsub(".*-", "", fg008$snps_for_medi)))

cl <- read.csv("data/chr_length_B73v4.csv")
fg008 <- newpos(d=fg008, GAP=5e+06, cl)

names(hlgene)[4] <- "pos"
hlgene <- newpos(d=hlgene, GAP=5e+06, cl)

fg008$end <- 550111694
names(fg008)[9] <- "start"

tb$Var1 <- gsub("-", "_", tb$Var1)
tb$chr <- as.numeric(as.character(gsub("_.*", "", tb$Var1)))
tb$pos <- as.numeric(as.character(gsub(".*_", "", tb$Var1)))



out = data.frame(start=0, end=120616133)
plot_mht_ellipse(inputdf=tb, edf=fg008, col2plot="Freq", jmph=FALSE, cl_file="data/chr_length_B73v4.csv", pl=TRUE,
         ylab="Indirect SNPs Freq",  cex = 0.6)



```











