---
title: "New mediation analysis results: indirect SNPs"
author: "Jinliang Yang"
date: "1-20-2021"
output: NULL
---


## Normalize the path:

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) 
knitr::opts_knit$set(root.dir=normalizePath('../../')) 
```

### Pheno prepared by Zhikai

```{r}
library("data.table")

ag_trait <- fread("data/geno_trait.txt")
m_trait <- fread("data/metabolite_rep1_genotype_namecorrect.txt")
trait_category <- data.frame(category = "other", trait = c(colnames(ag_trait)[-1], colnames(m_trait)[-1]))
trait_category$category <- as.character(trait_category$category)

### Assign trait type
trait_category$category[c(3,4,11:13,38)]= "Flowering Time"
trait_category$category[c(6,23)]= "Development"
trait_category$category[c(15,16,36)]= "Leaf Morphology"
trait_category$category[c(32,33)]= "Male Inflorescence"
trait_category$category[c(1,7,9,8)]= "Female Inflorescence"
trait_category$category[c(2,10,35,37,39,40)]= "Seed Traits"
trait_category$category[41:106]= "Metabolite"

pvm = fread("/common/jyanglab/zhikaiyang/projects/mediation/largedata/pvm_742rows_ag_met.csv")
pvm = merge(pvm, trait_category, by = "trait", all.x = T, sort = F)


#heritability
h2 = data.frame(category = "other", trait = colnames(ag_trait)[-1], h2 = 0)
h2$category <- as.character(h2$category)
h2$category[c(3,4,11:13,38)]= "Flowering Time"
h2$category[c(6,23)]= "Development"
h2$category[c(15,16,36)]= "Leaf Morphology"
h2$category[c(32,33)]= "Male Inflorescence"
h2$category[c(1,7,9,8)]= "Female Inflorescence"
h2$category[c(2,10,35,37,39,40)]= "Seed Traits"
h2 = arrange(h2, category, trait)



h2_new = h2 
h2_new$h2[c(9,16,17,2,15,14,13,40,3,1,4,35,39)] = c(0.73,0.29,0.37,0.4,0.34,0.3,0.49,0.11,0.17,0.21,0.31,0.30,0.27)





h2$h2[c(7,9,8,2,1,13,14,15,16,17,3,4,6,5,36,35,39,40,37)] = c(0.33, 0.71, 0.70, 0.56, 0.59, 0.60, 0.59, 0.50, 0.62, 0.66, 0.42, 0.37, 0.43, 0.24, 0.26, 0.42, 0.23, 0.35, 0.29 )


h2s = subset(h2, h2>0)

h2_new_s = subset(h2_new, h2 >0)
# h2s_stat = (h2s %>% group_by(category) %>% summarise(avg_h2 = mean(h2), median_h2 = median(h2), min_h2 = min(h2), max_h2 = max(h2), std_h2 = var(h2), num = n()))
# h2s_stat = arrange(h2s_stat, avg_h2)
# h2s_max = h2s_stat[,c(1,5)]
```


## PVM and h2

```{r}
df <- merge(pvm, h2s[,2:3], by="trait")
write.table(df, "cache/trait_pvm_h2.csv", sep=",", row.names = FALSE, quote=FALSE)


df = merge(pvm, h2_new_s[,2:3], by = "trait")
```


# Plot PVM with h2

```{r}
library(ggplot2)
df <- read.csv("cache/trait_pvm_h2.csv")
df <- subset(df, pmed.pure < 0.8)
fsize=18
df$tissue <- factor(df$tissue, levels = c( "GRoot", "GShoot", "L3Base", "L3Tip", "LMAD", "LMAN","Kern"),
                    labels =c( "Germinating Root", "Germinating Shoot", "Leaf 3 base", "Leaf 3 tip", "Adult leaf during the day", "Adult leaf at night","Kernels after pollination"))

set.seed(1234)
cor_list = replicate(2000, cor.test(sample(df1$pmed.pure), sample(df1$h2))$estimat)
sum(cor_list >= 0.665676)
# 99

df1 <- subset(df, tissue %in% "Adult leaf during the day")
p1 <- ggplot(df1, aes(x=h2, y=pmed.pure, color=category)) +
    #geom_bar(stat="identity", position=position_dodge()) +
    geom_point(size=3) +
    geom_smooth(method=lm, linetype="solid",
             color="darkred", fill="grey") +
    # facet_wrap(~ tissue) +
    xlab("Heritability") +
    ylab("Proportion of Variance Mediated(PVM)") +
    ggtitle("") +
    theme_classic() +
    labs(color = "") +
    #scale_y_continuous(limits = c(-0.01, 1)) +
    theme(plot.title = element_text(size=20, face = "bold"), 
          axis.text=element_text(size=16, face="bold"),
          strip.text.x = element_text(size = 16, face = "bold"),
          axis.title=element_text(size=fsize-2, face="bold"),
          #axis.text.x = element_text(angle = 15, hjust=0.8),
          legend.position = c(0.3, 0.85), 
          legend.title = element_text(size=fsize-2, face="bold"),
          legend.text = element_text(size=fsize-2))
p1

pdf("graphs/med_h2_LMAD.pdf", width = 6, height= 6)
p1
dev.off()
```


#Excuding adult leaf during the day:

```{r}
library(ggplot2)
df <- read.csv("cache/trait_pvm_h2.csv")
df <- subset(df, pmed.pure < 0.8)
fsize=18
df$tissue <- factor(df$tissue, levels = c( "GRoot", "GShoot", "L3Base", "L3Tip", "LMAD", "LMAN","Kern"),
                    labels =c( "Germinating Root", "Germinating Shoot", "Leaf 3 base", "Leaf 3 tip", "Adult leaf during the day", "Adult leaf at night","Kernels after pollination"))


df2 <- subset(df, tissue != "Adult leaf during the day")
p2 <- ggplot(df2, aes(x=h2, y=pmed.pure, color=category)) +
    #geom_bar(stat="identity", position=position_dodge()) +
    geom_point(size=3) +
    geom_smooth(method=lm, linetype="dashed",
             color="darkred", fill="grey") +
    facet_wrap(~ tissue) +
    xlab("Heritability") +
    ylab("Proportion of Variance Mediated(PVM)") +
    ggtitle("") +
    theme_classic() +
    labs(color = "") +
    scale_y_continuous(limits = c(-0.15, 0.3)) +
    theme(plot.title = element_text(size=20, face = "bold"), 
          axis.text=element_text(size=16, face="bold"),
          strip.text.x = element_text(size = 16, face = "bold"),
          axis.title=element_text(size=fsize-2, face="bold"),
          #axis.text.x = element_text(angle = 15, hjust=0.8),
          legend.position = "top", 
          legend.title = element_text(size=fsize-2, face="bold"),
          legend.text = element_text(size=fsize-2))
p2

pdf("graphs/med_h2_others.pdf", width = 10, height= 10)
p2
dev.off()


```
