---
title: "Run array job for mediation analysis"
output: NULL
author: Jinliang Yang
date: 9-24-2020
---


```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE) 
knitr::opts_knit$set(root.dir=normalizePath('../../')) 
#library(tidyverse)
```


### Run an array job!

```{r}
rfile <- list.files(path="largedata/RNA-seq", pattern="csv", full.names=TRUE)
trait <- read.delim("data/geno_trait.txt", header=T)
  
df <- data.frame(rnafile=rep(rfile, each=40), trait=rep(2:41, times=7))
write.table(df, "largedata/df_job_control_arg.csv", sep=",", row.names=FALSE, quote=FALSE)
write.table(df, "largedata/df_job_control_arg.csv", sep=",", row.names=FALSE,quote=FALSE)
```



```{r}
library("huskeR")
run_Rcode(inputdf=data.frame(file=1:280, out=NA), outdir="slurm-script", cmdno = 4, 
          rcodes = "profiling/2_mediation/2.B.1_setup_med_job.R",
          rversion="3.5",
          base_shid = "med_test",
          email="zhikaiyang911@gmail.com", 
          runinfo = c(FALSE, "batch", 16, "200G", "12:00:00"))
###>>> In this path: cd /common/jyanglab/jyang21/projects/mediation
###>>> RUN: sbatch -p batch --licenses=common --nodes=1 --ntasks=16 --mem 200G --time=12:00:00 slurm-script/med_test_array.sh
```




### Run an array job for population 368!

```{r}
rfile <- list.files(path="largedata/RNA-seq", pattern="P368", full.names=TRUE)
trait <- read.delim("data/blup_368_traits_final_NA.txt", header=T)
  
df <- data.frame(rnafile=rep(rfile, each=17), trait=rep(2:18, times=1))
write.table(df, "largedata/df_job_control_arg_P368.csv", sep=",", row.names=FALSE, quote=FALSE)
write.table(df, "largedata/df_job_control_arg_P368.csv", sep=",", row.names=FALSE,quote=FALSE)
```

###run for population 368
```{r}
library("huskeR")
run_Rcode(inputdf=data.frame(file=1:17, out=NA), outdir="slurm-script", cmdno = 3, 
          rcodes = "profiling/2_mediation/2.B.1_setup_med_job.R",
          rversion="3.5",
          base_shid = "med_test",
          email="zhikaiyang911@gmail.com", 
          runinfo = c(FALSE, "batch", 16, "200G", "9:00:00"))
###>>> In this path: cd /common/jyanglab/jyang21/projects/mediation
###>>> RUN: sbatch -p batch --licenses=common --nodes=1 --ntasks=16 --mem 200G --time=9:00:00 slurm-script/med_test_array.sh
```




