---
title: "Plot PVM"
author: "Jinliang Yang"
date: "09-08-2020"
output: NULL
---


## Normalize the path:

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) 
knitr::opts_knit$set(root.dir=normalizePath('../../')) 
```

### read in data

```{r}

f <- list.files(path="data/", pattern="p7msnps_r", full.names = T)

out <- data.frame()
for(i in 1:length(f)){
  tem <- read.csv(f[i], header=TRUE)
  tem$snp <- "p7m"
  tem$file <- f[i]
  out <- rbind(out, tem)
}

out$trait  <- gsub(".*proportion_|_p7m.*", "", out$file)

```

### Assign category

Zhikai, double-check the trait category assignment!
```{r}
library(ggplot2)
# library(ggpubr)
library(dplyr)

df <- subset(out, method %in% "medfixbic")
df$trait <- as.character(df$trait)

### assign category: 
df$cat <- "1"
# df[df$trait %in% c("asi", "daystosilk", "daystotassel", "gddasi", "gddtosilk", "gddtoassel"), ]$cat <- "Flowering"
df[df$trait %in% c("asi", "daystosilk", "daystotassel"), ]$cat <- "Flowering"
df[df$trait %in% c("eh", "planth"), ]$cat <- "Development"
df[df$trait %in% c("ll", "lw", "ula"), ]$cat <- "Leaf morphology"
df[df$trait %in% c("cobd", "cobl", "cobw", "knum", "ern"), ]$cat <- "Inflorescence"
df[df$trait %in% c("earm", "tkv", "twkw"), ]$cat <- "Seed traits"

table(df$cat)
```


### Visualization p7m

```{r}
library(ggplot2)
# library(ggpubr)
library(dplyr)

fsize=18
df$tissue <- factor(df$tissue, levels = c("kern", "groot", "gs", "l3b", "l3t", "ld268", "ln268"),
                    labels =c("Kernels after pollination", "Germinating Root", "Germinating Shoot", "Leaf 3 base", "Leaf 3 tip", "Adult leaf during the day", "Adult leaf at night"))

```


```{r}
df1 <- subset(df, cat %in% "Flowering")

p1 <- ggplot(df1, aes(y=tissue, x=pmed.pure, fill=tissue)) +
    #geom_bar(stat="identity", position=position_dodge()) +
    geom_boxplot(outlier.colour="black", outlier.shape=16, 
             outlier.size=2, notch=FALSE) +
    scale_fill_manual(values=rep("#69b3a2", 7), guide=FALSE) +
    # scale_fill_viridis(discrete = TRUE, alpha=0.6) +
    geom_jitter(color="#cc4141", size=2, alpha=0.9) +
    xlab("") +
    ylab("") +
    ggtitle("Flowering Time Traits") +
    theme_classic() +
    scale_x_continuous(limits = c(-0.01, 1)) +
    theme(plot.title = element_text(size=20, face = "bold"), 
          axis.text=element_text(size=16, face="bold"),
          strip.text.x = element_text(size = 16, face = "bold"),
          axis.title=element_text(size=fsize, face="bold"),
          # axis.text.x = element_text(angle = 20),
          legend.position = "none", 
          legend.title = element_text(size=fsize, face="bold"),
          legend.text = element_text(size=fsize))
p1


```

```{r}
df2 <- subset(df, cat %in% "Seed traits")
p2 <- ggplot(df2, aes(y=tissue, x=pmed.pure, fill=tissue)) +
    #geom_bar(stat="identity", position=position_dodge()) +
    geom_boxplot(outlier.colour="black", outlier.shape=16, 
             outlier.size=2, notch=FALSE) +
    scale_fill_manual(values=rep("#cdc0b0", 7), guide=FALSE) +
    # scale_fill_viridis(discrete = TRUE, alpha=0.6) +
    geom_jitter(color="#cc4141", size=2, alpha=0.9) +
    xlab("Proportion of variance mediated") +
    ylab("") +
    ggtitle("Seed Traits") +
    theme_classic() +
    scale_x_continuous(limits = c(-0.01, 1)) +
    theme(plot.title = element_text(size=20, face = "bold"), 
          axis.text=element_text(size=16, face="bold"),
          strip.text.x = element_text(size = 16, face = "bold"),
          axis.title=element_text(size=fsize, face="bold"),
          # axis.text.x = element_text(angle = 20),
          legend.position = "none", 
          legend.title = element_text(size=fsize, face="bold"),
          legend.text = element_text(size=fsize))
p2
```

```{r}
df3 <- subset(df, cat %in% "Leaf morphology")

p3 <- ggplot(df3, aes(y=tissue, x=pmed.pure, fill=tissue)) +
    #geom_bar(stat="identity", position=position_dodge()) +
    geom_boxplot(outlier.colour="black", outlier.shape=16, 
             outlier.size=2, notch=FALSE) +
    scale_fill_manual(values=rep("#69b3a2", 7), guide=FALSE) +
    # scale_fill_viridis(discrete = TRUE, alpha=0.6) +
    geom_jitter(color="#cc4141", size=2, alpha=0.9) +
    xlab("Proportion of variance mediated") +
    ylab("") +
    ggtitle("Leaf morphology") +
    theme_classic() +
    scale_x_continuous(limits = c(-0.01, 1)) +
    theme(plot.title = element_text(size=20, face = "bold"), 
          axis.text=element_text(size=16, face="bold"),
          strip.text.x = element_text(size = 16, face = "bold"),
          axis.title=element_text(size=fsize, face="bold"),
          # axis.text.x = element_text(angle = 20),
          legend.position = "none", 
          legend.title = element_text(size=fsize, face="bold"),
          legend.text = element_text(size=fsize))
p3
```

```{r}
df4 <- subset(df, cat %in% "Inflorescence")

p4 <- ggplot(df4, aes(y=tissue, x=pmed.pure, fill=tissue)) +
    #geom_bar(stat="identity", position=position_dodge()) +
    geom_boxplot(outlier.colour="black", outlier.shape=16, 
             outlier.size=2, notch=FALSE) +
    scale_fill_manual(values=rep("#69b3a2", 7), guide=FALSE) +
    # scale_fill_viridis(discrete = TRUE, alpha=0.6) +
    geom_jitter(color="#cc4141", size=2, alpha=0.9) +
    xlab("Proportion of variance mediated") +
    ylab("") +
    ggtitle("Inflorescence") +
    theme_classic() +
    scale_x_continuous(limits = c(-0.01, 1)) +
    theme(plot.title = element_text(size=20, face = "bold"), 
          axis.text=element_text(size=16, face="bold"),
          strip.text.x = element_text(size = 16, face = "bold"),
          axis.title=element_text(size=fsize, face="bold"),
          # axis.text.x = element_text(angle = 20),
          legend.position = "none", 
          legend.title = element_text(size=fsize, face="bold"),
          legend.text = element_text(size=fsize))
p4
```


```{r}
df5 <- subset(df, cat %in% "Development")
p5 <- ggplot(df5, aes(y=tissue, x=pmed.pure, fill=tissue)) +
    #geom_bar(stat="identity", position=position_dodge()) +
    geom_boxplot(outlier.colour="black", outlier.shape=16, 
             outlier.size=2, notch=FALSE) +
    scale_fill_manual(values=rep("#69b3a2", 7), guide=FALSE) +
    # scale_fill_viridis(discrete = TRUE, alpha=0.6) +
    geom_jitter(color="#cc4141", size=2, alpha=0.9) +
    xlab("Proportion of variance mediated") +
    ylab("") +
    ggtitle("Development") +
    theme_classic() +
    scale_x_continuous(limits = c(-0.01, 1)) +
    theme(plot.title = element_text(size=20, face = "bold"), 
          axis.text=element_text(size=16, face="bold"),
          strip.text.x = element_text(size = 16, face = "bold"),
          axis.title=element_text(size=fsize, face="bold"),
          # axis.text.x = element_text(angle = 20),
          legend.position = "none", 
          legend.title = element_text(size=fsize, face="bold"),
          legend.text = element_text(size=fsize))
p5
```




```{r}
library(cowplot)

pdf("graphs/pvm_flowering_seed.pdf", width = 7, height= 8)
plot_grid(p1, p2, labels = "AUTO", nrow=2, ncol=1, label_size = 20, align = "v")
dev.off()
```


