---
title: "med_further_exploration_visual_1"
author: "Zhikai Yang"
date: "May 25th, 2020"
output: NULL
---


## Normalize the path:

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) 
knitr::opts_knit$set(root.dir=normalizePath('../../')) 
```
### read in data
```{r}
daystosilk_p4msnps <- read.csv("data/med_proportion_daystosilk_p4msnps_r.csv", header=TRUE)
daystosilk_p4msnps$snps <- rep("p4m", nrow(daystosilk_p4msnps))
daystosilk_p4msnps$trait <- rep("daystosilk", nrow(daystosilk_p4msnps))
daystosilk_p4msnps$tissue  <- factor(daystosilk_p4msnps$tissue, levels=c("gs", "groot", "l3t", "l3b", "ld268", "ln268", "kern"))

daystotassel_p4msnps <- read.csv("data/med_proportion_daystotassel_p4msnps_r.csv", header=TRUE)
daystotassel_p4msnps$snps <- rep("p4m", nrow(daystotassel_p4msnps))
daystotassel_p4msnps$trait <- rep("daystotassel", nrow(daystotassel_p4msnps))
daystotassel_p4msnps$tissue  <- factor(daystotassel_p4msnps$tissue, levels=c("gs", "groot", "l3t", "l3b", "ld268", "ln268", "kern"))

planth_p4msnps <- read.csv("data/med_proportion_planth_p4msnps_r.csv", header=TRUE)
planth_p4msnps$snps <- rep("p4m", nrow(planth_p4msnps))
planth_p4msnps$trait <- rep("planth", nrow(planth_p4msnps))
planth_p4msnps$tissue  <- factor(planth_p4msnps$tissue, levels=c("gs", "groot", "l3t", "l3b", "ld268", "ln268", "kern"))

cobd_p4msnps <- read.csv("data/med_proportion_cobd_p4msnps_r.csv", header=TRUE)
cobd_p4msnps$snps <- rep("p4m", nrow(cobd_p4msnps))
cobd_p4msnps$trait <- rep("cobd", nrow(cobd_p4msnps))
cobd_p4msnps$tissue  <- factor(cobd_p4msnps$tissue, levels=c("gs", "groot", "l3t", "l3b", "ld268", "ln268", "kern"))

cobw_p4msnps <- read.csv("data/med_proportion_cobw_p4msnps_r.csv", header=TRUE)
cobw_p4msnps$snps <- rep("p4m", nrow(cobw_p4msnps))
cobw_p4msnps$trait <- rep("cobw", nrow(cobw_p4msnps))
cobw_p4msnps$tissue  <- factor(cobw_p4msnps$tissue, levels=c("gs", "groot", "l3t", "l3b", "ld268", "ln268", "kern"))

tkv_p4msnps <- read.csv("data/med_proportion_tkv_p4msnps_r.csv", header=TRUE)
tkv_p4msnps$snps <- rep("p4m", nrow(tkv_p4msnps))
tkv_p4msnps$trait <- rep("tkv", nrow(tkv_p4msnps))
tkv_p4msnps$tissue  <- factor(tkv_p4msnps$tissue, levels=c("gs", "groot", "l3t", "l3b", "ld268", "ln268", "kern"))

earm_p4msnps <- read.csv("data/med_proportion_earm_p4msnps_r.csv", header=TRUE)
earm_p4msnps$snps <- rep("p4m", nrow(earm_p4msnps))
earm_p4msnps$trait <- rep("earm", nrow(earm_p4msnps))
earm_p4msnps$tissue  <- factor(earm_p4msnps$tissue, levels=c("gs", "groot", "l3t", "l3b", "ld268", "ln268", "kern"))

ekpr_p4msnps <- read.csv("data/med_proportion_ekpr_p4msnps_r.csv", header=TRUE)
ekpr_p4msnps$snps <- rep("p4m", nrow(ekpr_p4msnps))
ekpr_p4msnps$trait <- rep("ekpr", nrow(ekpr_p4msnps))
ekpr_p4msnps$tissue  <- factor(ekpr_p4msnps$tissue, levels=c("gs", "groot", "l3t", "l3b", "ld268", "ln268", "kern"))

ern_p4msnps <- read.csv("data/med_proportion_ern_p4msnps_r.csv", header=TRUE)
ern_p4msnps$snps <- rep("p4m", nrow(ern_p4msnps))
ern_p4msnps$trait <- rep("ern", nrow(ern_p4msnps))
ern_p4msnps$tissue  <- factor(ern_p4msnps$tissue, levels=c("gs", "groot", "l3t", "l3b", "ld268", "ln268", "kern"))

cobl_p4msnps <- read.csv("data/med_proportion_cobl_p4msnps_r.csv", header=TRUE)
cobl_p4msnps$snps <- rep("p4m", nrow(cobl_p4msnps))
cobl_p4msnps$trait <- rep("cobl", nrow(cobl_p4msnps))
cobl_p4msnps$tissue  <- factor(cobl_p4msnps$tissue, levels=c("gs", "groot", "l3t", "l3b", "ld268", "ln268", "kern"))

tpb_p4msnps <- read.csv("data/med_proportion_tpb_p4msnps_r.csv", header=TRUE)
tpb_p4msnps$snps <- rep("p4m", nrow(tpb_p4msnps))
tpb_p4msnps$trait <- rep("tpb", nrow(tpb_p4msnps))
tpb_p4msnps$tissue  <- factor(tpb_p4msnps$tissue, levels=c("gs", "groot", "l3t", "l3b", "ld268", "ln268", "kern"))

tsl_p4msnps <- read.csv("data/med_proportion_tsl_p4msnps_r.csv", header=TRUE)
tsl_p4msnps$snps <- rep("p4m", nrow(tsl_p4msnps))
tsl_p4msnps$trait <- rep("tsl", nrow(tsl_p4msnps))
tsl_p4msnps$tissue  <- factor(tsl_p4msnps$tissue, levels=c("gs", "groot", "l3t", "l3b", "ld268", "ln268", "kern"))

lw_p4msnps <- read.csv("data/med_proportion_lw_p4msnps_r.csv", header=TRUE)
lw_p4msnps$snps <- rep("p4m", nrow(lw_p4msnps))
lw_p4msnps$trait <- rep("lw", nrow(lw_p4msnps))
lw_p4msnps$tissue  <- factor(lw_p4msnps$tissue, levels=c("gs", "groot", "l3t", "l3b", "ld268", "ln268", "kern"))

ll_p4msnps <- read.csv("data/med_proportion_ll_p4msnps_r.csv", header=TRUE)
ll_p4msnps$snps <- rep("p4m", nrow(ll_p4msnps))
ll_p4msnps$trait <- rep("ll", nrow(ll_p4msnps))
ll_p4msnps$tissue  <- factor(ll_p4msnps$tissue, levels=c("gs", "groot", "l3t", "l3b", "ld268", "ln268", "kern"))

eh_p4msnps <- read.csv("data/med_proportion_eh_p4msnps_r.csv", header=TRUE)
eh_p4msnps$snps <- rep("p4m", nrow(eh_p4msnps))
eh_p4msnps$trait <- rep("eh", nrow(eh_p4msnps))
eh_p4msnps$tissue  <- factor(eh_p4msnps$tissue, levels=c("gs", "groot", "l3t", "l3b", "ld268", "ln268", "kern"))

asi_p4msnps <- read.csv("data/med_proportion_asi_p4msnps_r.csv", header=TRUE)
asi_p4msnps$snps <- rep("p4m", nrow(asi_p4msnps))
asi_p4msnps$trait <- rep("asi", nrow(asi_p4msnps))
asi_p4msnps$tissue  <- factor(asi_p4msnps$tissue, levels=c("gs", "groot", "l3t", "l3b", "ld268", "ln268", "kern"))

ula_p4msnps <- read.csv("data/med_proportion_ula_p4msnps_r.csv", header=TRUE)
ula_p4msnps$snps <- rep("p4m", nrow(ula_p4msnps))
ula_p4msnps$trait <- rep("ula", nrow(ula_p4msnps))
ula_p4msnps$tissue  <- factor(ula_p4msnps$tissue, levels=c("gs", "groot", "l3t", "l3b", "ld268", "ln268", "kern"))

twkw_p4msnps <- read.csv("data/med_proportion_twkw_p4msnps_r.csv", header=TRUE)
twkw_p4msnps$snps <- rep("p4m", nrow(twkw_p4msnps))
twkw_p4msnps$trait <- rep("twkw", nrow(twkw_p4msnps))
twkw_p4msnps$tissue  <- factor(twkw_p4msnps$tissue, levels=c("gs", "groot", "l3t", "l3b", "ld268", "ln268", "kern"))

knum_p4msnps <- read.csv("data/med_proportion_knum_p4msnps_r.csv", header=TRUE)
knum_p4msnps$snps <- rep("p4m", nrow(knum_p4msnps))
knum_p4msnps$trait <- rep("knum", nrow(knum_p4msnps))
knum_p4msnps$tissue  <- factor(knum_p4msnps$tissue, levels=c("gs", "groot", "l3t", "l3b", "ld268", "ln268", "kern"))

kw_p4msnps <- read.csv("data/med_proportion_kw_p4msnps_r.csv", header=TRUE)
kw_p4msnps$snps <- rep("p4m", nrow(kw_p4msnps))
kw_p4msnps$trait <- rep("kw", nrow(kw_p4msnps))
kw_p4msnps$tissue  <- factor(kw_p4msnps$tissue, levels=c("gs", "groot", "l3t", "l3b", "ld268", "ln268", "kern"))

df <- rbind(asi_p4msnps, daystotassel_p4msnps, daystosilk_p4msnps, planth_p4msnps, eh_p4msnps, ll_p4msnps, lw_p4msnps, ula_p4msnps, tsl_p4msnps, tpb_p4msnps, cobd_p4msnps, cobl_p4msnps, ern_p4msnps, ekpr_p4msnps, earm_p4msnps, cobw_p4msnps, kw_p4msnps, twkw_p4msnps, knum_p4msnps)

df$trait <- factor(df$trait, levels =c("asi", "daystotassel", "daystosilk", "planth", "eh", "ll", "lw", "ula", "tsl", "tpb", "cobd", "cobl", "ern", "ekpr", "earm", "cobw", "kw", "twkw", "knum") )

```

### Visualization p4m
```{r}
library(ggplot2)
library(ggpubr)
library(dplyr)

df_medfix0.5 <- filter(df, method %in% c("medfix0.5"))

p11 <- ggplot(data=df_medfix0.5[1:70,], aes(x=trait, y=pmed.pure, fill=tissue)) +
geom_bar(stat="identity", position=position_dodge())+ ylim(0, max(df$pmed.pure))+
  theme(text = element_text(size=40))+
  #geom_text(aes(label=pmed.pure), vjust=1.6, color="white",
  #         position = position_dodge(0.9), size=3.5)+
  scale_fill_brewer(palette="Paired")+ ggtitle("medfix0.5")+
  theme_minimal()

p12 <- ggplot(data=df_medfix0.5[71:133,], aes(x=trait, y=pmed.pure, fill=tissue)) +
geom_bar(stat="identity", position=position_dodge())+ ylim(0, max(df$pmed.pure))+
  theme(text = element_text(size=40))+
  #geom_text(aes(label=pmed.pure), vjust=1.6, color="white",
  #         position = position_dodge(0.9), size=3.5)+
  scale_fill_brewer(palette="Paired")+ ggtitle("medfix0.5")+
  theme_minimal()

ggarrange(p11, p12, 
          ncol = 1, nrow = 2)


df_medfixbic <- filter(df, method %in% c("medfixbic"))

p13 <- ggplot(data=df_medfixbic[1:70,], aes(x=trait, y=pmed.pure, fill=tissue)) +
geom_bar(stat="identity", position=position_dodge())+ ylim(0, max(df$pmed.pure))+
  theme(text = element_text(size=40))+
  #geom_text(aes(label=pmed.pure), vjust=1.6, color="white",
  #         position = position_dodge(0.9), size=3.5)+
  scale_fill_brewer(palette="Paired")+ ggtitle("medfixbic")+
  theme_minimal()

p14 <- ggplot(data=df_medfixbic[71:133,], aes(x=trait, y=pmed.pure, fill=tissue)) +
geom_bar(stat="identity", position=position_dodge())+ ylim(0, max(df$pmed.pure))+
  theme(text = element_text(size=40))+
  #geom_text(aes(label=pmed.pure), vjust=1.6, color="white",
  #         position = position_dodge(0.9), size=3.5)+
  scale_fill_brewer(palette="Paired")+ ggtitle("medfixbic")+
  theme_minimal()

ggarrange(p13, p14, 
          ncol = 1, nrow = 2)


ggarrange(p11, p12, p13, p14,
          ncol = 1, nrow = 4)

```

```{r}


p21 <- ggplot(data=df_medfix0.5[1:70,], aes(x=trait, y=n.med, fill=tissue)) +
geom_bar(stat="identity", position=position_dodge())+ ylim(0, max(df$n.med))+
  theme(text = element_text(size=40))+
  #geom_text(aes(label=n.med), vjust=1.6, color="white",
  #         position = position_dodge(0.9), size=3.5)+
  scale_fill_brewer(palette="Paired")+ ggtitle("medfix0.5")+
  theme_minimal()

p22 <- ggplot(data=df_medfix0.5[71:133,], aes(x=trait, y=n.med, fill=tissue)) +
geom_bar(stat="identity", position=position_dodge())+ ylim(0, max(df$n.med))+
  theme(text = element_text(size=40))+
  #geom_text(aes(label=n.med), vjust=1.6, color="white",
  #         position = position_dodge(0.9), size=3.5)+
  scale_fill_brewer(palette="Paired")+ ggtitle("medfix0.5")+
  theme_minimal()

ggarrange(p21, p22, 
          ncol = 1, nrow = 2)


df_medfixbic <- filter(df, method %in% c("medfixbic"))

p23 <- ggplot(data=df_medfixbic[1:70,], aes(x=trait, y=n.med, fill=tissue)) +
geom_bar(stat="identity", position=position_dodge())+ ylim(0, max(df$n.med))+
  theme(text = element_text(size=40))+
  #geom_text(aes(label=n.med), vjust=1.6, color="white",
  #         position = position_dodge(0.9), size=3.5)+
  scale_fill_brewer(palette="Paired")+ ggtitle("medfixbic")+
  theme_minimal()

p24 <- ggplot(data=df_medfixbic[71:133,], aes(x=trait, y=n.med, fill=tissue)) +
geom_bar(stat="identity", position=position_dodge())+ ylim(0, max(df$n.med))+
  theme(text = element_text(size=40))+
  #geom_text(aes(label=n.med), vjust=1.6, color="white",
  #         position = position_dodge(0.9), size=3.5)+
  scale_fill_brewer(palette="Paired")+ ggtitle("medfixbic")+
  theme_minimal()

ggarrange(p23, p24, 
          ncol = 1, nrow = 2)


ggarrange(p21, p22, p23, p24,
          ncol = 1, nrow = 4)
```

### Correlation between med.pure and Heritablity
```{r}
df_medfix <- filter(df, method %in% c("medfix0.5", "medfixbic"))

df_medfix$hp <- c(rep(0.33, 14), rep(0.71, 14), rep(0.70, 14), rep(0.56, 14), rep(0.59, 14), rep(0.60, 14), rep(0.59, 14), rep(0.50, 14), rep(0.62, 14), rep(0.66, 14), rep(0.42, 14), rep(0.37, 14), rep(0.43, 14), rep(0.24, 14), rep(0.26, 14), rep(0.42, 14), rep(0.23, 14), rep(0.35, 14), rep(0.29, 14)) 


df_medfix$method_snps <- rep("fill", nrow(df_medfix))

df_medfix$method_snps = paste(as.character(df_medfix$method) , as.character(df_medfix$snps), sep= "_")

df_medfix <- filter(df_medfix, method %in% c("medfix0.5","medfixbic"))

df_medfix_gs <- filter(df_medfix, tissue %in% c("gs"))
p31 <- ggplot(df_medfix_gs, aes(x=hp, y=pmed.pure, color=method_snps, shape=method_snps)) +
  geom_point()+ ggtitle("gs") + 
  geom_smooth(method=lm ,se=FALSE, fullrange=TRUE)

df_medfix_groot <- filter(df_medfix, tissue %in% c("groot"))
p32 <- ggplot(df_medfix_groot, aes(x=hp, y=pmed.pure, color=method_snps, shape=method_snps)) +
  geom_point()+ ggtitle("groot") + 
  geom_smooth(method=lm ,se=FALSE, fullrange=TRUE)

df_medfix_l3t <- filter(df_medfix, tissue %in% c("l3t"))
p33 <- ggplot(df_medfix_l3t, aes(x=hp, y=pmed.pure, color=method_snps, shape=method_snps)) +
  geom_point()+ ggtitle("l3t") + 
  geom_smooth(method=lm ,se=FALSE, fullrange=TRUE)

df_medfix_l3b <- filter(df_medfix, tissue %in% c("l3b"))
p34 <- ggplot(df_medfix_l3b, aes(x=hp, y=pmed.pure, color=method_snps, shape=method_snps)) +
  geom_point()+ ggtitle("l3b") + 
  geom_smooth(method=lm ,se=FALSE, fullrange=TRUE)

df_medfix_ld268 <- filter(df_medfix, tissue %in% c("ld268"))
p35 <- ggplot(df_medfix_ld268, aes(x=hp, y=pmed.pure, color=method_snps, shape=method_snps)) +
  geom_point()+ ggtitle("ld268") + 
  geom_smooth(method=lm ,se=FALSE, fullrange=TRUE)

df_medfix_ln268 <- filter(df_medfix, tissue %in% c("ln268"))
p36 <- ggplot(df_medfix_ln268, aes(x=hp, y=pmed.pure, color=method_snps, shape=method_snps)) +
  geom_point()+ ggtitle("ln268") + 
  geom_smooth(method=lm ,se=FALSE, fullrange=TRUE)

df_medfix_kern <- filter(df_medfix, tissue %in% c("kern"))
p37 <- ggplot(df_medfix_kern, aes(x=hp, y=pmed.pure, color=method_snps, shape=method_snps)) +
  geom_point()+ ggtitle("kern") + 
  geom_smooth(method=lm ,se=FALSE, fullrange=TRUE)

df_medfixbic_p4m <- filter(df_medfix, method_snps %in% c("medfixbic_p4m"))
p38 <- ggplot(df_medfixbic_p4m, aes(x=hp, y=pmed.pure, color=tissue, shape=tissue)) +
  geom_point()+ ggtitle("medfixbic_p4m") + 
  geom_smooth(method=lm ,se=FALSE, fullrange=TRUE)
  
df_medfixbic_p4m <- filter(df_medfix, method_snps %in% c("medfixbic_p4m"))
p39 <- ggplot(df_medfixbic_p4m, aes(x=hp, y=pmed.pure, color=tissue, shape=tissue)) +
  geom_point()+ ggtitle("medfixbic_p4m") + 
  geom_smooth(method=lm ,se=FALSE, fullrange=TRUE)


ggarrange(p31, p33, p35, p37, p32, p34 ,p36, p38,
          ncol = 4, nrow = 2)

ggarrange(p38, p39,
          ncol = 1, nrow = 2)


```

correlation test
```{r}
df_daystosilk <- filter(df_medfix, trait %in% c("daystosilk"))
df_daystosilk <- arrange(df_daystosilk, tissue)
df_cor <- data.frame(tissue = df_daystosilk$tissue, method_snps = df_daystosilk$method_snps, estimate = rep(0, nrow(df_daystosilk)), p_val = rep(0, nrow(df_daystosilk)))

df_cor$tissue_method_snps = paste(as.character(df_cor$tissue) , as.character(df_cor$method_snps), sep= "_")

##gs

#medfix0.5_p4m
df_gs_medfix0.5_p4m <- filter(df_medfix, tissue %in% c("gs"), method_snps %in% c("medfix0.5_p4m"))
idx = which (df_cor$tissue_method_snps == "gs_medfix0.5_p4m" )
df_cor[idx,4] =  (cor.test(df_gs_medfix0.5_p4m$pmed.pure, df_gs_medfix0.5_p4m$hp, method = "pearson"))[[3]]
df_cor[idx,3] =  (cor.test(df_gs_medfix0.5_p4m$pmed.pure, df_gs_medfix0.5_p4m$hp, method = "pearson"))[[4]]


#medfixbic_p4m
df_gs_medfixbic_p4m <- filter(df_medfix, tissue %in% c("gs"), method_snps %in% c("medfixbic_p4m"))
idx = which (df_cor$tissue_method_snps == "gs_medfixbic_p4m" )
df_cor[idx,4] =  (cor.test(df_gs_medfixbic_p4m$pmed.pure, df_gs_medfixbic_p4m$hp, method = "pearson"))[[3]]
df_cor[idx,3] =  (cor.test(df_gs_medfixbic_p4m$pmed.pure, df_gs_medfixbic_p4m$hp, method = "pearson"))[[4]]



##groot

#medfix0.5_p4m
df_groot_medfix0.5_p4m <- filter(df_medfix, tissue %in% c("groot"), method_snps %in% c("medfix0.5_p4m"))
idx = which (df_cor$tissue_method_snps == "groot_medfix0.5_p4m" )
df_cor[idx,4] =  (cor.test(df_groot_medfix0.5_p4m$pmed.pure, df_groot_medfix0.5_p4m$hp, method = "pearson"))[[3]]
df_cor[idx,3] =  (cor.test(df_groot_medfix0.5_p4m$pmed.pure, df_groot_medfix0.5_p4m$hp, method = "pearson"))[[4]]


#medfixbic_p4m
df_groot_medfixbic_p4m <- filter(df_medfix, tissue %in% c("groot"), method_snps %in% c("medfixbic_p4m"))
idx = which (df_cor$tissue_method_snps == "groot_medfixbic_p4m" )
df_cor[idx,4] =  (cor.test(df_groot_medfixbic_p4m$pmed.pure, df_groot_medfixbic_p4m$hp, method = "pearson"))[[3]]
df_cor[idx,3] =  (cor.test(df_groot_medfixbic_p4m$pmed.pure, df_groot_medfixbic_p4m$hp, method = "pearson"))[[4]]


##l3t

#medfix0.5_p4m
df_l3t_medfix0.5_p4m <- filter(df_medfix, tissue %in% c("l3t"), method_snps %in% c("medfix0.5_p4m"))
idx = which (df_cor$tissue_method_snps == "l3t_medfix0.5_p4m" )
df_cor[idx,4] =  (cor.test(df_l3t_medfix0.5_p4m$pmed.pure, df_l3t_medfix0.5_p4m$hp, method = "pearson"))[[3]]
df_cor[idx,3] =  (cor.test(df_l3t_medfix0.5_p4m$pmed.pure, df_l3t_medfix0.5_p4m$hp, method = "pearson"))[[4]]


#medfixbic_p4m
df_l3t_medfixbic_p4m <- filter(df_medfix, tissue %in% c("l3t"), method_snps %in% c("medfixbic_p4m"))
idx = which (df_cor$tissue_method_snps == "l3t_medfixbic_p4m" )
df_cor[idx,4] =  (cor.test(df_l3t_medfixbic_p4m$pmed.pure, df_l3t_medfixbic_p4m$hp, method = "pearson"))[[3]]
df_cor[idx,3] =  (cor.test(df_l3t_medfixbic_p4m$pmed.pure, df_l3t_medfixbic_p4m$hp, method = "pearson"))[[4]]


##l3b

#medfix0.5_p4m
df_l3b_medfix0.5_p4m <- filter(df_medfix, tissue %in% c("l3b"), method_snps %in% c("medfix0.5_p4m"))
idx = which (df_cor$tissue_method_snps == "l3b_medfix0.5_p4m" )
df_cor[idx,4] =  (cor.test(df_l3b_medfix0.5_p4m$pmed.pure, df_l3b_medfix0.5_p4m$hp, method = "pearson"))[[3]]
df_cor[idx,3] =  (cor.test(df_l3b_medfix0.5_p4m$pmed.pure, df_l3b_medfix0.5_p4m$hp, method = "pearson"))[[4]]


#medfixbic_p4m
df_l3b_medfixbic_p4m <- filter(df_medfix, tissue %in% c("l3b"), method_snps %in% c("medfixbic_p4m"))
idx = which (df_cor$tissue_method_snps == "l3b_medfixbic_p4m" )
df_cor[idx,4] =  (cor.test(df_l3b_medfixbic_p4m$pmed.pure, df_l3b_medfixbic_p4m$hp, method = "pearson"))[[3]]
df_cor[idx,3] =  (cor.test(df_l3b_medfixbic_p4m$pmed.pure, df_l3b_medfixbic_p4m$hp, method = "pearson"))[[4]]


##ld268

#medfix0.5_p4m
df_ld268_medfix0.5_p4m <- filter(df_medfix, tissue %in% c("ld268"), method_snps %in% c("medfix0.5_p4m"))
idx = which (df_cor$tissue_method_snps == "ld268_medfix0.5_p4m" )
df_cor[idx,4] =  (cor.test(df_ld268_medfix0.5_p4m$pmed.pure, df_ld268_medfix0.5_p4m$hp, method = "pearson"))[[3]]
df_cor[idx,3] =  (cor.test(df_ld268_medfix0.5_p4m$pmed.pure, df_ld268_medfix0.5_p4m$hp, method = "pearson"))[[4]]


#medfixbic_p4m
df_ld268_medfixbic_p4m <- filter(df_medfix, tissue %in% c("ld268"), method_snps %in% c("medfixbic_p4m"))
idx = which (df_cor$tissue_method_snps == "ld268_medfixbic_p4m" )
df_cor[idx,4] =  (cor.test(df_ld268_medfixbic_p4m$pmed.pure, df_ld268_medfixbic_p4m$hp, method = "pearson"))[[3]]
df_cor[idx,3] =  (cor.test(df_ld268_medfixbic_p4m$pmed.pure, df_ld268_medfixbic_p4m$hp, method = "pearson"))[[4]]


##ln268

#medfix0.5_p4m
df_ln268_medfix0.5_p4m <- filter(df_medfix, tissue %in% c("ln268"), method_snps %in% c("medfix0.5_p4m"))
idx = which (df_cor$tissue_method_snps == "ln268_medfix0.5_p4m" )
df_cor[idx,4] =  (cor.test(df_ln268_medfix0.5_p4m$pmed.pure, df_ln268_medfix0.5_p4m$hp, method = "pearson"))[[3]]
df_cor[idx,3] =  (cor.test(df_ln268_medfix0.5_p4m$pmed.pure, df_ln268_medfix0.5_p4m$hp, method = "pearson"))[[4]]


#medfixbic_p4m
df_ln268_medfixbic_p4m <- filter(df_medfix, tissue %in% c("ln268"), method_snps %in% c("medfixbic_p4m"))
idx = which (df_cor$tissue_method_snps == "ln268_medfixbic_p4m" )
df_cor[idx,4] =  (cor.test(df_ln268_medfixbic_p4m$pmed.pure, df_ln268_medfixbic_p4m$hp, method = "pearson"))[[3]]
df_cor[idx,3] =  (cor.test(df_ln268_medfixbic_p4m$pmed.pure, df_ln268_medfixbic_p4m$hp, method = "pearson"))[[4]]


##kern

#medfix0.5_p4m
df_kern_medfix0.5_p4m <- filter(df_medfix, tissue %in% c("kern"), method_snps %in% c("medfix0.5_p4m"))
idx = which (df_cor$tissue_method_snps == "kern_medfix0.5_p4m" )
df_cor[idx,4] =  (cor.test(df_kern_medfix0.5_p4m$pmed.pure, df_kern_medfix0.5_p4m$hp, method = "pearson"))[[3]]
df_cor[idx,3] =  (cor.test(df_kern_medfix0.5_p4m$pmed.pure, df_kern_medfix0.5_p4m$hp, method = "pearson"))[[4]]


#medfixbic_p4m
df_kern_medfixbic_p4m <- filter(df_medfix, tissue %in% c("kern"), method_snps %in% c("medfixbic_p4m"))
idx = which (df_cor$tissue_method_snps == "kern_medfixbic_p4m" )
df_cor[idx,4] =  (cor.test(df_kern_medfixbic_p4m$pmed.pure, df_kern_medfixbic_p4m$hp, method = "pearson"))[[3]]
df_cor[idx,3] =  (cor.test(df_kern_medfixbic_p4m$pmed.pure, df_kern_medfixbic_p4m$hp, method = "pearson"))[[4]]



p41 <- ggplot(data=df_cor, aes(x=tissue, y=p_val, fill=method_snps)) +
geom_bar(stat="identity", position=position_dodge())+ ylim(0, max(df$pmed.pure))+
  geom_abline(slope=0, intercept=0.05,  col = "yellow",lty=2) +
  geom_abline(slope=0, intercept=0.1,  col = "black",lty=2) +
  scale_fill_brewer(palette="Paired")+ ggtitle("p-val vs tissue(method_snps)")+
  theme_minimal()



p42 <- ggplot(data=df_cor, aes(x=tissue, y=estimate, fill=method_snps)) +
geom_bar(stat="identity", position=position_dodge())+
  scale_fill_brewer(palette="Paired")+ ggtitle("estimate vs tissue(method_snps)")+
  theme_minimal()



ggarrange(p42, p41, 
          ncol = 1, nrow = 2)

```


