---
title: "Collect mediation analysis results"
author: "Zhikai Yang "
date: "11-2-2020"
output: NULL
---


## Normalize the path:

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) 
knitr::opts_knit$set(root.dir=normalizePath('../../')) 
```

### Pheno prepared by Zhikai

```{r}
library("data.table")

ag_trait <- fread("data/geno_trait.txt")
m_trait <- fread("data/metabolite_rep1_genotype_namecorrect.txt")
trait_category <- data.frame(category = "other", trait = c(colnames(ag_trait)[-1], colnames(m_trait)[-1]))
trait_category$category <- as.character(trait_category$category)

### Assign trait type
trait_category$category[c(3,4,11:13,38)]= "Flowering Time"
trait_category$category[c(6,23)]= "Development"
trait_category$category[c(15,16,36)]= "Leaf Morphology"
trait_category$category[c(32,33)]= "Male Inflorescence"
trait_category$category[c(1,7,9,8)]= "Female Inflorescence"
trait_category$category[c(2,10,35,37,39,40)]= "Seed Traits"
trait_category$category[41:106]= "Metabolite"

pvm = fread("/common/jyanglab/zhikaiyang/projects/mediation/largedata/med_output/pvm_742rows_ag_met.csv")
pvm = merge(pvm, trait_category, by = "trait", all.x = T, sort = F)


#heritability
h2 = data.frame(category = "other", trait = colnames(ag_trait)[-1], h2 = 0)
h2$category[c(3,4,11:13,38)]= "Flowering Time"
h2$category[c(6,23)]= "Development"
h2$category[c(15,16,36)]= "Leaf Morphology"
h2$category[c(32,33)]= "Male Inflorescence"
h2$category[c(1,7,9,8)]= "Female Inflorescence"
h2$category[c(2,10,35,37,39,40)]= "Seed Traits"
h2 = arrange(h2, category, trait)
h2$h2[c(7,9,8,2,1,13,14,15,16,17,3,4,6,5,36,35,39,40,37)] = c(0.33, 0.71, 0.70, 0.56, 0.59, 0.60, 0.59, 0.50, 0.62, 0.66, 0.42, 0.37, 0.43, 0.24, 0.26, 0.42, 0.23, 0.35, 0.29 )
h2s = subset(h2, h2>0)
h2s_stat = (h2s %>% group_by(category) %>% summarise(avg_h2 = mean(h2), median_h2 = median(h2), min_h2 = min(h2), max_h2 = max(h2), std_h2 = var(h2), num = n()))
h2s_stat = arrange(h2s_stat, avg_h2)
h2s_max = h2s_stat[,c(1,5)]
```


### New Geno on HCC

```{r}

f <- list.files(path="/common/jyanglab/zhikaiyang/projects/mediation/largedata/med_output/", pattern="pcut_sum_", full.names = T)
fmic <- list.files(path="/common/jyanglab/zhikaiyang/projects/mediation/largedata/med_output/", pattern="pcut_sum_T[[0-9]", full.names = T)
id = which(f %in% fmic)
f = f[-c(id)]
id = grep("P368", f)
f = f[-c(id)]

out <- data.frame()
for(i in 1:length(f)){
  tem <- read.csv(f[i], header=TRUE)
  tem$file <- f[i]
  out <- rbind(out, tem)
}

out$file  <- gsub(".*\\/", "", out$file)

library(data.table)

# method
out$method <- gsub(".pcut.*", "", out$file)
# tissue type
out$tissue <- gsub(".*_ts_|.csv", "", out$file)
table(out$tissue)
# trait
out$trait <- gsub(".*sum_|_ts.*", "", out$file)
table(out$trait)
id = which(out$trait == "Nitrogen")
out = out[-id,]
write.table(out, "largedata/pvm_742rows_ag_met.csv", sep=",", row.names=FALSE, quote=FALSE)
```


### on local

```{r}
library(data.table)
library(dplyr)
library(agricolae)
library(ggplot2)
  
  
ag_trait <- fread("data/geno_trait.txt")
m_trait <- fread("data/metabolite_rep1_genotype_namecorrect.txt")
trait_category <- data.frame(category = "other", trait = c(colnames(ag_trait)[-1], colnames(m_trait)[-1]))

trait_category$category[c(3,4,11:13,38)]= "Flowering Time"
trait_category$category[c(6,23)]= "Development"
trait_category$category[c(15,16,36)]= "Leaf Morphology"
trait_category$category[c(32,33)]= "Male Inflorescence"
trait_category$category[c(1,7,9,8)]= "Female Inflorescence"
trait_category$category[c(2,10,35,37,39,40)]= "Seed Traits"
trait_category$category[41:106]= "Metabolite"

pvm = fread("largedata/pvm_742rows_ag_met.csv")
pvm = merge(pvm, trait_category, by = "trait", all.x = T, sort = F)


#heritability
h2 = data.frame(category = "other", trait = colnames(ag_trait)[-1], h2 = 0)
h2$category[c(3,4,11:13,38)]= "Flowering Time"
h2$category[c(6,23)]= "Development"
h2$category[c(15,16,36)]= "Leaf Morphology"
h2$category[c(32,33)]= "Male Inflorescence"
h2$category[c(1,7,9,8)]= "Female Inflorescence"
h2$category[c(2,10,35,37,39,40)]= "Seed Traits"
h2 = arrange(h2, category, trait)
h2$h2[c(7,9,8,2,1,13,14,15,16,17,3,4,6,5,36,35,39,40,37)] = c(0.33, 0.71, 0.70, 0.56, 0.59, 0.60, 0.59, 0.50, 0.62, 0.66, 0.42, 0.37, 0.43, 0.24, 0.26, 0.42, 0.23, 0.35, 0.29 )
h2s = subset(h2, h2>0)
h2s_stat = (h2s %>% group_by(category) %>% summarise(avg_h2 = mean(h2), median_h2 = median(h2), min_h2 = min(h2), max_h2 = max(h2), std_h2 = var(h2), num = n()))
h2s_stat = arrange(h2s_stat, avg_h2)
h2s_max = h2s_stat[,c(1,5)]


h2s$category <- factor(h2s$category, levels = c( "Seed Traits", "Female Inflorescence", "Leaf Morphology", "Development", "Flowering Time", "Male Inflorescence"),
                    labels =c( "Seed Traits", "Female Inflorescence", "Leaf Morphology", "Development", "Flowering Time", "Male Inflorescence"))

hsd=HSD.test(aov(h2~category,data=h2s), "category", group=T)

p <- ggboxplot(h2s, x = "category", y = "h2",
            color = "category", palette = "jco", add = "jitter")
#p <- ggboxplot(h2s, aes(x=reorder(category, h2, FUN = mean)), y = "h2",
#          color = "category", palette = "jco",
#          add = "jitter")+geom_text(data=h2s_max,aes(x=category,y=h2,label=hsd$groups$groups),vjust=0)

p_cat = p + 
  xlab("Category") +
    ylab("Heritablity ") +
    ggtitle("") +
    theme_classic() +
    labs(fill = "") +
    scale_y_continuous(limits = c(-0.01, 1)) +
    theme(plot.title = element_text(size=20, face = "bold"), 
          axis.text=element_text(size=12, face="bold"),
          strip.text.x = element_text(size = 16, face = "bold"),
          axis.title=element_text(size=fsize, face="bold"),
          axis.text.x = element_text(angle = 15, hjust=0.8),
          legend.position = "right", 
          legend.title = element_text(size=10, face="bold"),
          legend.text = element_text(size=10))

pdf("graphs/heritability_cat.pdf", width = 9, height= 6)
p_cat
dev.off()


#iris.summarized = iris %>% group_by(Species) %>% summarize(Max.Petal.Length=max(Petal.Length))
#hsd=HSD.test(aov(Petal.Length~Species,data=iris), "Species", group=T)
#ggplot(iris,aes(x=reorder(Species,Petal.Length,FUN = median),y=Petal.Length))+geom_boxplot()+geom_text(data=iris.summarized,aes(x=Species,y=0.2+Max.Petal.Length,label=hsd$groups$groups),vjust=0)



#####
pvm_stat = (pvm %>% group_by(trait) %>% summarise(avg_pvm = mean(pmed.pure) ,avg_vmed = mean(v.med), min_vmed = min(v.med), max_vmed = max(v.med), num = n()))
ag_mean = apply(ag_trait[,2:ncol(ag_trait)], 2, mean , na.rm = T)
ag_mean = as.data.frame(ag_mean)
ag_var = apply(ag_trait[,2:ncol(ag_trait)], 2, var , na.rm = T)
ag_var = as.data.frame(ag_var)
colnames(ag_var) = "trait_var"

m_mean = apply(m_trait[,2:ncol(m_trait)], 2, mean , na.rm = T)
m_mean = as.data.frame(m_mean)
m_var = apply(m_trait[,2:ncol(m_trait)], 2, var , na.rm = T)
m_var = as.data.frame(m_var)
colnames(m_var) = "trait_var"

trait_var = rbind(ag_var, m_var)
trait_var$trait = rownames(trait_var)
pvm_stat = merge(pvm_stat, trait_var, by = "trait")
####



######subset out other, bi cat###
pvm_s = subset(pvm, category != "other")

id = which(pvm_s$category != "Metabolite")
pvm_s$category[id] = "Agronomy"


library(ggplot2)
library(ggpubr)
fsize =16
p <-ggplot(pvm, aes(x=category, y=pmed.pure, fill=tissue)) +
  geom_boxplot(outlier.colour="black", outlier.shape=16, outlier.size=1, notch=FALSE) +
   xlab("Trait Category") +
    ylab("Proportion of the Variance Mediated (PVM) ") +
    ggtitle("") +
    theme_classic() +
    labs(fill = "") +
    scale_y_continuous(limits = c(-0.01, 1)) +
    stat_compare_means(method = "t.test")+
    theme(plot.title = element_text(size=20, face = "bold"), 
          axis.text=element_text(size=16, face="bold"),
          strip.text.x = element_text(size = 16, face = "bold"),
          axis.title=element_text(size=fsize, face="bold"),
          axis.text.x = element_text(angle = 15, hjust=0.8),
          legend.position = "right", 
          legend.title = element_text(size=fsize, face="bold"),
          legend.text = element_text(size=fsize))

t.test(pvm$pmed.pure[id], pvm$pmed.pure[-id])
mean(pvm$pmed.pure[id])
mean(pvm$pmed.pure[-id], na.rm = T)

pdf("graphs/pvm_box_ag_met.pdf", width = 9, height= 6)
p
dev.off()

pvm_s$tissue <- factor(pvm_s$tissue, levels = c( "GRoot", "GShoot", "L3Base", "L3Tip", "LMAD", "LMAN","Kern"),
                    labels =c( "Germinating Root", "Germinating Shoot", "Leaf 3 base", "Leaf 3 tip", "Adult leaf during the day", "Adult leaf at night","Kernels after pollination"))
pvm_s$category = as.factor(pvm_s$category)

p <- ggboxplot(pvm_s, x = "tissue", y = "pmed.pure",
          color = "category", palette = "jco",
          add = "jitter")
p_tissue = p + stat_compare_means(aes(group = category), label = "p.signif")+
  xlab("Tissue") +
    ylab("Proportion of the Variance Mediated (PVM) ") +
    ggtitle("") +
    theme_classic() +
    labs(fill = "") +
    scale_y_continuous(limits = c(-0.01, 1)) +
    theme(plot.title = element_text(size=20, face = "bold"), 
          axis.text=element_text(size=16, face="bold"),
          strip.text.x = element_text(size = 16, face = "bold"),
          axis.title=element_text(size=fsize, face="bold"),
          axis.text.x = element_text(angle = 15, hjust=0.8),
          legend.position = "top", 
          legend.title = element_text(size=fsize, face="bold"),
          legend.text = element_text(size=fsize))

pdf("graphs/pvm_s_box_ag_met_tissue.pdf", width = 9, height= 6)
p_tissue
dev.off()


#################subset out other and metabolite, not bi###
pvm_s = subset(pvm, !(category %in% c("other", "Metabolite")))

pvm_s$category <- factor(pvm_s$category, levels = c( "Seed Traits", "Female Inflorescence", "Leaf Morphology", "Development", "Flowering Time", "Male Inflorescence"),
                    labels =c( "Seed Traits", "Female Inflorescence", "Leaf Morphology", "Development", "Flowering Time", "Male Inflorescence"))





pvm_s$tissue <- factor(pvm_s$tissue, levels = c( "GRoot", "GShoot", "L3Base", "L3Tip", "LMAD", "LMAN","Kern"),
                    labels =c( "Germinating Root", "Germinating Shoot", "Leaf 3 base", "Leaf 3 tip", "Adult leaf during the day", "Adult leaf at night","Kernels after pollination"))


p <- ggboxplot(pvm_s, x = "tissue", y = "pmed.pure",
          color = "category", palette = "jco",
          add = "jitter")
p_tissue = p + 
  xlab("Tissue") +
    ylab("Proportion of the Variance Mediated (PVM) ") +
    ggtitle("") +
    theme_classic() +
    labs(fill = "") +
    scale_y_continuous(limits = c(-0.01, 1)) +
    theme(plot.title = element_text(size=20, face = "bold"), 
          axis.text=element_text(size=13, face="bold"),
          strip.text.x = element_text(size = 13, face = "bold"),
          axis.title=element_text(size=fsize, face="bold"),
          axis.text.x = element_text(angle = 15, hjust=0.8),
          legend.position = "right", 
          legend.title = element_text(size=12, face="bold"),
          legend.text = element_text(size=12))

pdf("graphs/pvm_s_box_ags_tissue.pdf", width = 9, height= 6)
p_tissue
dev.off()

























p <- ggboxplot(pvm, x = "tissue", y = "pmed.pure",
          color = "category")

p_tissue_cats = p +
  xlab("Tissue") +
    ylab("Proportion of the Variance Mediated (PVM) ") +
    ggtitle("") +
    theme_classic() +
    labs(fill = "") +
    scale_y_continuous(limits = c(-0.01, 1)) +
    theme(plot.title = element_text(size=20, face = "bold"), 
          axis.text=element_text(size=16, face="bold"),
          strip.text.x = element_text(size = 16, face = "bold"),
          axis.title=element_text(size=fsize, face="bold"),
          axis.text.x = element_text(angle = 15, hjust=0.8),
          legend.position = "right", 
          legend.title = element_text(size=fsize, face="bold"),
          legend.text = element_text(size=fsize))



pdf("graphs/pvm_box_cats_tissue.pdf", width = 9, height= 6)
p_tissue_cats
dev.off()



```
