---
title: "Run array job for MedMix Simulation"
output: NULL
author: Jinliang Yang
date: 12-27-2021
---


```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE) 
knitr::opts_knit$set(root.dir=normalizePath('../../')) 
#library(tidyverse)
```


### Run an array job!

```{r}
df <- data.frame(nQTLper=c(rep(10,90), rep(50,90), rep(100,90)), 
                 nQTLar=rep(c(rep(10,30), rep(50,30), rep(100,30)),3),
                 h2_as=rep(c(rep(0.25,10), rep(0.5,10), rep(0.75,10)),9),
                 seed=rep(1231:1240,27)
                 )
write.table(df, "profiling/8.simulation/df_job_control_medmix.csv", sep=",", row.names=FALSE, quote=FALSE)

```



```{r}
library("huskeR")
run_Rcode(inputdf=data.frame(file=1:3, out=0), outdir="slurm-script", cmdno = 1, 
          rcodes = "profiling/8.simulation/8.A.1_setup_medmix_job.R",
          rversion="3.5",
          base_shid = "medmix",
          email="zhikaiyang911@gmail.com", 
          runinfo = c(TRUE, "batch", 4, "60G", "12:00:00"))
###>>> In this path: cd /common/jyanglab/zhikaiyang/projects/mediation
###>>> RUN: sbatch -p batch --licenses=common --nodes=1 --ntasks=16 --mem 200G --time=30:00:00 slurm-script/med_test_array.sh
```






